token = 'xmivhpghsxzccbbnf69eb002036f2118'
tracking_id = ''
#
os_type = 'linux'
os_name = 'os_name' 
os_version = 'os_version' 
product = 'product' 

[package]
package_id = 65
package_version = '0.0.300'

[build]
mode = 'release' #debug

[log]
log_to_file = true
log_dir = "logs"
print_logo = true
level = 'INFO'

[server]
host = 'gtxvdqvuweqs.com'
port = 5060

[satellite]
port = 36060
